### ISSUE TITLE
text input filter

### ISSUE THREAD

**Issue by tongtoanbs** [ndm2/ckeditor-placeholder-elements#11]
Hi friend,

I'm using your plugin in combo mode, it's really good. But now I have more and more items in the richcombo. And my client is asking about the text filter inside the dropdown. Can you show me how I can achieve this?

Kind Regards

**Comment by ndm2** [comment]
I don't really get what exactly you mean by "_the text filter_", if you are referring to a plugin or similar, then please mention that.

In case you are looking for a not-yet existent functionality that searches/filters elements in a dropdown, then this is a little out of scope for this issue tracker. At the very best this would be a feature request, but I wouldn't hold my breath, as I don't see me implementing something like that anytime soon - if at all.

**Comment by tongtoanbs** [comment]
yes I'm looking for a searches/filters elements in a dropdown

**Comment by ndm2** [comment]
I see... but as I said, I don't think that I'm going to implement something like that anytime soon - sorry.

**Comment by tongtoanbs** [comment]
yep, thank you very much

**Comment by ndm2** [comment]
Closing for now. It's been quite some time, and there are no plans to implement that feature.
