### ISSUE TITLE
NPM support is missing

### ISSUE THREAD

**Issue by iamveecee** [ndm2/ckeditor-placeholder-elements#16]
Hi @ndm2 ,  Thanks for this plugin, I used it on my projects via bower.  I was wondering that did you published the plugin on the NPM. I am asking because I want to use it with npm and didn't find your plugin their.  Could you publish it there too.

Thanks!

**Comment by ndm2** [comment]
Should be very much possible. I'm very busy currently, but I'll look into it some day next week.

**Comment by ndm2** [comment]
The plugin is now available via npm.

https://www.npmjs.com/package/@ndm2/ckeditor-placeholder-elements
