### ISSUE TITLE
Javascript error on element.$.innerText 

### ISSUE THREAD

**Issue by ronan-paul** [ndm2/ckeditor-placeholder-elements#2]
There is a hook on selectionChange in plugin.js which generates an error when element.$.innerText is not defined. 
I have to admit that I did not understand what the code was doing exactly, but I propose to adapt the code to avoid the error on line 209: 
									if (element.$.innerText)
									{
										var text = element.$.innerText.toString();
										if(text !== currentValue && text.match(regexp))
										{
											this.setValue(text, placeholdersMap[text].label);
											return;
										}
									}

**Comment by ndm2** [comment]
The code is responsible for changing the selected item in the placeholders combobox in case a placeholder is selected/deselected in the editor.

Can you provide an example that triggers the error? I'd rather not make changes without knowing the exact underlying cause of the problem.

**Comment by ndm2** [comment]
The code is responsible for changing the selected item in the placeholders combobox in case a placeholder is selected/deselected in the editor.

Can you provide an example that triggers the error? I'd rather not make changes without knowing the exact underlying cause of the problem.

**Comment by profet23** [comment]
```innerText``` is not supported by firefox... should be changed to the more standard ```textContent```.
As here: 1c7948562ab45bb2592bfe5ea1fa2e7b7a0cd9fc

**Comment by ndm2** [comment]
Fixed in #6
